title: FreeBSD Github Migration Proposal
description: Proposal for Github migration of the FreeBSD project from Bugzilla/Phabricator/MoinMoin
theme: just-the-docs

url: https://fel1x-developer.github.io/freebsd-github-migration

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
